package pfe.migration.server.ejb.bdd.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the LANG_INFO table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="LANG_INFO"
 */
public abstract class BaseLangInfo  implements Serializable {

	public static String PROP_LANG_SYMBOLIC = "LangSymbolic";
	public static String PROP_LANG_LANGUAGE = "LangLanguage";
	public static String PROP_LANG_ISO_CODE = "LangIsoCode";
	public static String PROP_LANG_ENV_VARIABLE = "LangEnvVariable";
	public static String PROP_LANG_MS_LOCAL_ID_HEXA = "LangMsLocalIdHexa";
	public static String PROP_LANG_MS_LOCAL_ID = "LangMsLocalId";
	public static String PROP_LANG_CODE = "LangCode";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.String _langLanguage;

	// fields
	private java.lang.String _langMsLocalId;
	private java.lang.String _langIsoCode;
	private java.lang.String _langSymbolic;
	private java.lang.String _langEnvVariable;
	private java.lang.String _langMsLocalIdHexa;
	private java.lang.Integer _langCode;


	// constructors
	public BaseLangInfo () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseLangInfo (java.lang.String _langLanguage) {
		this.setLangLanguage(_langLanguage);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="lang_language"
     */
	public java.lang.String getLangLanguage () {
		return _langLanguage;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _langLanguage the new ID
	 */
	public void setLangLanguage (java.lang.String _langLanguage) {
		this._langLanguage = _langLanguage;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: lang_ms_local_id
	 */
	public java.lang.String getLangMsLocalId () {
		return _langMsLocalId;
	}

	/**
	 * Set the value related to the column: lang_ms_local_id
	 * @param _langMsLocalId the lang_ms_local_id value
	 */
	public void setLangMsLocalId (java.lang.String _langMsLocalId) {
		this._langMsLocalId = _langMsLocalId;
	}


	/**
	 * Return the value associated with the column: lang_iso_code
	 */
	public java.lang.String getLangIsoCode () {
		return _langIsoCode;
	}

	/**
	 * Set the value related to the column: lang_iso_code
	 * @param _langIsoCode the lang_iso_code value
	 */
	public void setLangIsoCode (java.lang.String _langIsoCode) {
		this._langIsoCode = _langIsoCode;
	}


	/**
	 * Return the value associated with the column: lang_symbolic
	 */
	public java.lang.String getLangSymbolic () {
		return _langSymbolic;
	}

	/**
	 * Set the value related to the column: lang_symbolic
	 * @param _langSymbolic the lang_symbolic value
	 */
	public void setLangSymbolic (java.lang.String _langSymbolic) {
		this._langSymbolic = _langSymbolic;
	}


	/**
	 * Return the value associated with the column: lang_env_variable
	 */
	public java.lang.String getLangEnvVariable () {
		return _langEnvVariable;
	}

	/**
	 * Set the value related to the column: lang_env_variable
	 * @param _langEnvVariable the lang_env_variable value
	 */
	public void setLangEnvVariable (java.lang.String _langEnvVariable) {
		this._langEnvVariable = _langEnvVariable;
	}


	/**
	 * Return the value associated with the column: lang_ms_local_id_hexa
	 */
	public java.lang.String getLangMsLocalIdHexa () {
		return _langMsLocalIdHexa;
	}

	/**
	 * Set the value related to the column: lang_ms_local_id_hexa
	 * @param _langMsLocalIdHexa the lang_ms_local_id_hexa value
	 */
	public void setLangMsLocalIdHexa (java.lang.String _langMsLocalIdHexa) {
		this._langMsLocalIdHexa = _langMsLocalIdHexa;
	}


	/**
	 * Return the value associated with the column: lang_code
	 */
	public java.lang.Integer getLangCode () {
		return _langCode;
	}

	/**
	 * Set the value related to the column: lang_code
	 * @param _langCode the lang_code value
	 */
	public void setLangCode (java.lang.Integer _langCode) {
		this._langCode = _langCode;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof pfe.migration.server.ejb.bdd.base.BaseLangInfo)) return false;
		else {
			pfe.migration.server.ejb.bdd.base.BaseLangInfo mObj = (pfe.migration.server.ejb.bdd.base.BaseLangInfo) obj;
			if (null == this.getLangLanguage() || null == mObj.getLangLanguage()) return false;
			else return (this.getLangLanguage().equals(mObj.getLangLanguage()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getLangLanguage()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getLangLanguage().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}