package pfe.migration.server.ejb.bdd.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the global_conf table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="global_conf"
 */
public abstract class BaseGlobalConf  implements Serializable {

	public static String PROP_GLOBAL_HOSTNAME = "GlobalHostname";
	public static String PROP_GLOBAL_KEY = "GlobalKey";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _globalKey;

	// fields
	private java.lang.String _globalHostname;


	// constructors
	public BaseGlobalConf () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseGlobalConf (java.lang.Integer _globalKey) {
		this.setGlobalKey(_globalKey);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="global_key"
     */
	public java.lang.Integer getGlobalKey () {
		return _globalKey;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _globalKey the new ID
	 */
	public void setGlobalKey (java.lang.Integer _globalKey) {
		this._globalKey = _globalKey;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: global_hostname
	 */
	public java.lang.String getGlobalHostname () {
		return _globalHostname;
	}

	/**
	 * Set the value related to the column: global_hostname
	 * @param _globalHostname the global_hostname value
	 */
	public void setGlobalHostname (java.lang.String _globalHostname) {
		this._globalHostname = _globalHostname;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof pfe.migration.server.ejb.bdd.base.BaseGlobalConf)) return false;
		else {
			pfe.migration.server.ejb.bdd.base.BaseGlobalConf mObj = (pfe.migration.server.ejb.bdd.base.BaseGlobalConf) obj;
			if (null == this.getGlobalKey() || null == mObj.getGlobalKey()) return false;
			else return (this.getGlobalKey().equals(mObj.getGlobalKey()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getGlobalKey()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getGlobalKey().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}