package pfe.migration.server.ejb.bdd.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the users_data table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="users_data"
 */
public abstract class BaseUsersData  implements Serializable {

	public static String PROP_KEY = "Key";
	public static String PROP_TYPE = "Type";
	public static String PROP_LOGIN = "Login";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.String _key;

	// fields
	private java.lang.String _type;
	private java.lang.String _login;


	// constructors
	public BaseUsersData () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseUsersData (java.lang.String _key) {
		this.setKey(_key);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseUsersData (
		java.lang.String _key,
		java.lang.String _type,
		java.lang.String _login) {

		this.setKey(_key);
		this.setType(_type);
		this.setLogin(_login);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="key"
     */
	public java.lang.String getKey () {
		return _key;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _key the new ID
	 */
	public void setKey (java.lang.String _key) {
		this._key = _key;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: type
	 */
	public java.lang.String getType () {
		return _type;
	}

	/**
	 * Set the value related to the column: type
	 * @param _type the type value
	 */
	public void setType (java.lang.String _type) {
		this._type = _type;
	}


	/**
	 * Return the value associated with the column: login
	 */
	public java.lang.String getLogin () {
		return _login;
	}

	/**
	 * Set the value related to the column: login
	 * @param _login the login value
	 */
	public void setLogin (java.lang.String _login) {
		this._login = _login;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof pfe.migration.server.ejb.bdd.base.BaseUsersData)) return false;
		else {
			pfe.migration.server.ejb.bdd.base.BaseUsersData mObj = (pfe.migration.server.ejb.bdd.base.BaseUsersData) obj;
			if (null == this.getKey() || null == mObj.getKey()) return false;
			else return (this.getKey().equals(mObj.getKey()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getKey()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getKey().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}