package pfe.migration.server.ejb.bdd.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the USERS_DATA table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="USERS_DATA"
 */
public abstract class BaseUsersData  implements Serializable {

	public static String PROP_USERS_KEY = "UsersKey";
	public static String PROP_USERS_TYPE = "UsersType";
	public static String PROP_USERS_LOGIN = "UsersLogin";
	public static String PROP_USERS_PASS = "UsersPass";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _usersKey;
	private java.lang.String _usersLogin;
	private java.lang.String _usersPass;
	private java.lang.String _usersType;


	// constructors
	public BaseUsersData () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseUsersData (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="USERS_ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: USERS_KEY
	 */
	public java.lang.Integer getUsersKey () {
		return _usersKey;
	}

	/**
	 * Set the value related to the column: USERS_KEY
	 * @param _usersKey the USERS_KEY value
	 */
	public void setUsersKey (java.lang.Integer _usersKey) {
		this._usersKey = _usersKey;
	}


	/**
	 * Return the value associated with the column: USERS_LOGIN
	 */
	public java.lang.String getUsersLogin () {
		return _usersLogin;
	}

	/**
	 * Set the value related to the column: USERS_LOGIN
	 * @param _usersLogin the USERS_LOGIN value
	 */
	public void setUsersLogin (java.lang.String _usersLogin) {
		this._usersLogin = _usersLogin;
	}


	/**
	 * Return the value associated with the column: USERS_PASS
	 */
	public java.lang.String getUsersPass () {
		return _usersPass;
	}

	/**
	 * Set the value related to the column: USERS_PASS
	 * @param _usersPass the USERS_PASS value
	 */
	public void setUsersPass (java.lang.String _usersPass) {
		this._usersPass = _usersPass;
	}


	/**
	 * Return the value associated with the column: USERS_TYPE
	 */
	public java.lang.String getUsersType () {
		return _usersType;
	}

	/**
	 * Set the value related to the column: USERS_TYPE
	 * @param _usersType the USERS_TYPE value
	 */
	public void setUsersType (java.lang.String _usersType) {
		this._usersType = _usersType;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof pfe.migration.server.ejb.bdd.base.BaseUsersData)) return false;
		else {
			pfe.migration.server.ejb.bdd.base.BaseUsersData mObj = (pfe.migration.server.ejb.bdd.base.BaseUsersData) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}