package pfe.migration.server.ejb.bdd.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the network_dhcp_config table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="network_dhcp_config"
 */
public abstract class BaseNetworkDhcpConfig  implements Serializable {

	public static String PROP_DHCP_DEF_GATEWAY = "DhcpDefGateway";
	public static String PROP_DHCP_ENABLED = "DhcpEnabled";
	public static String PROP_DHCP_ADRESS = "DhcpAdress";
	public static String PROP_DHCP_SUBNETMASK = "DhcpSubnetmask";
	public static String PROP_DHCP_SEC_DNS = "DhcpSecDns";
	public static String PROP_DHCP_SERVER = "DhcpServer";
	public static String PROP_DHCP_DOMAIN = "DhcpDomain";
	public static String PROP_DHCP_KEY = "DhcpKey";
	public static String PROP_DHCP_PRI_DNS = "DhcpPriDns";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _dhcpKey;

	// fields
	private java.lang.String _dhcpDomain;
	private java.lang.String _dhcpDefGateway;
	private java.lang.String _dhcpServer;
	private java.lang.String _dhcpSubnetmask;
	private java.lang.String _dhcpPriDns;
	private java.lang.String _dhcpAdress;
	private java.lang.String _dhcpSecDns;
	private java.lang.Integer _dhcpEnabled;


	// constructors
	public BaseNetworkDhcpConfig () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseNetworkDhcpConfig (java.lang.Integer _dhcpKey) {
		this.setDhcpKey(_dhcpKey);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="dhcp_key"
     */
	public java.lang.Integer getDhcpKey () {
		return _dhcpKey;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _dhcpKey the new ID
	 */
	public void setDhcpKey (java.lang.Integer _dhcpKey) {
		this._dhcpKey = _dhcpKey;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: dhcp_domain
	 */
	public java.lang.String getDhcpDomain () {
		return _dhcpDomain;
	}

	/**
	 * Set the value related to the column: dhcp_domain
	 * @param _dhcpDomain the dhcp_domain value
	 */
	public void setDhcpDomain (java.lang.String _dhcpDomain) {
		this._dhcpDomain = _dhcpDomain;
	}


	/**
	 * Return the value associated with the column: dhcp_def_gateway
	 */
	public java.lang.String getDhcpDefGateway () {
		return _dhcpDefGateway;
	}

	/**
	 * Set the value related to the column: dhcp_def_gateway
	 * @param _dhcpDefGateway the dhcp_def_gateway value
	 */
	public void setDhcpDefGateway (java.lang.String _dhcpDefGateway) {
		this._dhcpDefGateway = _dhcpDefGateway;
	}


	/**
	 * Return the value associated with the column: dhcp_server
	 */
	public java.lang.String getDhcpServer () {
		return _dhcpServer;
	}

	/**
	 * Set the value related to the column: dhcp_server
	 * @param _dhcpServer the dhcp_server value
	 */
	public void setDhcpServer (java.lang.String _dhcpServer) {
		this._dhcpServer = _dhcpServer;
	}


	/**
	 * Return the value associated with the column: dhcp_subnetmask
	 */
	public java.lang.String getDhcpSubnetmask () {
		return _dhcpSubnetmask;
	}

	/**
	 * Set the value related to the column: dhcp_subnetmask
	 * @param _dhcpSubnetmask the dhcp_subnetmask value
	 */
	public void setDhcpSubnetmask (java.lang.String _dhcpSubnetmask) {
		this._dhcpSubnetmask = _dhcpSubnetmask;
	}


	/**
	 * Return the value associated with the column: dhcp_pri_dns
	 */
	public java.lang.String getDhcpPriDns () {
		return _dhcpPriDns;
	}

	/**
	 * Set the value related to the column: dhcp_pri_dns
	 * @param _dhcpPriDns the dhcp_pri_dns value
	 */
	public void setDhcpPriDns (java.lang.String _dhcpPriDns) {
		this._dhcpPriDns = _dhcpPriDns;
	}


	/**
	 * Return the value associated with the column: dhcp_adress
	 */
	public java.lang.String getDhcpAdress () {
		return _dhcpAdress;
	}

	/**
	 * Set the value related to the column: dhcp_adress
	 * @param _dhcpAdress the dhcp_adress value
	 */
	public void setDhcpAdress (java.lang.String _dhcpAdress) {
		this._dhcpAdress = _dhcpAdress;
	}


	/**
	 * Return the value associated with the column: dhcp_sec_dns
	 */
	public java.lang.String getDhcpSecDns () {
		return _dhcpSecDns;
	}

	/**
	 * Set the value related to the column: dhcp_sec_dns
	 * @param _dhcpSecDns the dhcp_sec_dns value
	 */
	public void setDhcpSecDns (java.lang.String _dhcpSecDns) {
		this._dhcpSecDns = _dhcpSecDns;
	}


	/**
	 * Return the value associated with the column: dhcp_enabled
	 */
	public java.lang.Integer getDhcpEnabled () {
		return _dhcpEnabled;
	}

	/**
	 * Set the value related to the column: dhcp_enabled
	 * @param _dhcpEnabled the dhcp_enabled value
	 */
	public void setDhcpEnabled (java.lang.Integer _dhcpEnabled) {
		this._dhcpEnabled = _dhcpEnabled;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof pfe.migration.server.ejb.bdd.base.BaseNetworkDhcpConfig)) return false;
		else {
			pfe.migration.server.ejb.bdd.base.BaseNetworkDhcpConfig mObj = (pfe.migration.server.ejb.bdd.base.BaseNetworkDhcpConfig) obj;
			if (null == this.getDhcpKey() || null == mObj.getDhcpKey()) return false;
			else return (this.getDhcpKey().equals(mObj.getDhcpKey()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getDhcpKey()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getDhcpKey().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}