package pfe.migration.server.ejb.bdd.base;

import net.sf.hibernate.Hibernate;
import net.sf.hibernate.Session;
import pfe.migration.server.ejb.bdd.dao.MandrakepkgsDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an automatically generated DAO class which should not be edited.
 */
public abstract class BaseMandrakepkgsDAO extends pfe.migration.server.ejb.bdd.dao._RootDAO {

	public static MandrakepkgsDAO instance;

	/**
	 * Return a singleton of the DAO
	 */
	public static MandrakepkgsDAO getInstance () {
		if (null == instance) instance = new MandrakepkgsDAO();
		return instance;
	}

	/**
	 * pfe.migration.server.ejb.bdd.dao._RootDAO _RootDAO.getReferenceClass()
	 */
	public Class getReferenceClass () {
		return pfe.migration.server.ejb.bdd.Mandrakepkgs.class;
	}
	
	public pfe.migration.server.ejb.bdd.Mandrakepkgs load(java.lang.Long key)
		throws net.sf.hibernate.HibernateException {
		return (pfe.migration.server.ejb.bdd.Mandrakepkgs) load(getReferenceClass(), key);
	}

	public pfe.migration.server.ejb.bdd.Mandrakepkgs load(java.lang.Long key, Session s)
		throws net.sf.hibernate.HibernateException {
		return (pfe.migration.server.ejb.bdd.Mandrakepkgs) load(getReferenceClass(), key, s);
	}

	public pfe.migration.server.ejb.bdd.Mandrakepkgs loadInitialize(java.lang.Long key, Session s) 
			throws net.sf.hibernate.HibernateException { 
		pfe.migration.server.ejb.bdd.Mandrakepkgs obj = load(key, s); 
		if (!Hibernate.isInitialized(obj)) {
			Hibernate.initialize(obj);
		} 
		return obj; 
	}

	/**
	 * Persist the given transient instance, first assigning a generated identifier. (Or using the current value
	 * of the identifier property if the assigned generator is used.) 
	 * @param mandrakepkgs a transient instance of a persistent class 
	 * @return the class identifier
	 */
	public java.lang.Long save(pfe.migration.server.ejb.bdd.Mandrakepkgs mandrakepkgs)
		throws net.sf.hibernate.HibernateException {
		return (java.lang.Long) super.save(mandrakepkgs);
	}

	/**
	 * Persist the given transient instance, first assigning a generated identifier. (Or using the current value
	 * of the identifier property if the assigned generator is used.) 
	 * Use the Session given.
	 * @param mandrakepkgs a transient instance of a persistent class
	 * @param s the Session
	 * @return the class identifier
	 */
	public java.lang.Long save(pfe.migration.server.ejb.bdd.Mandrakepkgs mandrakepkgs, Session s)
		throws net.sf.hibernate.HibernateException {
		return (java.lang.Long) super.save(mandrakepkgs, s);
	}

	/**
	 * Either save() or update() the given instance, depending upon the value of its identifier property. By default
	 * the instance is always saved. This behaviour may be adjusted by specifying an unsaved-value attribute of the
	 * identifier property mapping. 
	 * @param mandrakepkgs a transient instance containing new or updated state 
	 */
	public void saveOrUpdate(pfe.migration.server.ejb.bdd.Mandrakepkgs mandrakepkgs)
		throws net.sf.hibernate.HibernateException {
		super.saveOrUpdate(mandrakepkgs);
	}

	/**
	 * Either save() or update() the given instance, depending upon the value of its identifier property. By default the
	 * instance is always saved. This behaviour may be adjusted by specifying an unsaved-value attribute of the identifier
	 * property mapping. 
	 * Use the Session given.
	 * @param mandrakepkgs a transient instance containing new or updated state.
	 * @param s the Session.
	 */
	public void saveOrUpdate(pfe.migration.server.ejb.bdd.Mandrakepkgs mandrakepkgs, Session s)
		throws net.sf.hibernate.HibernateException {
		super.saveOrUpdate(mandrakepkgs, s);
	}

	/**
	 * Update the persistent state associated with the given identifier. An exception is thrown if there is a persistent
	 * instance with the same identifier in the current session.
	 * @param mandrakepkgs a transient instance containing updated state
	 */
	public void update(pfe.migration.server.ejb.bdd.Mandrakepkgs mandrakepkgs) 
		throws net.sf.hibernate.HibernateException {
		super.update(mandrakepkgs);
	}

	/**
	 * Update the persistent state associated with the given identifier. An exception is thrown if there is a persistent
	 * instance with the same identifier in the current session.
	 * Use the Session given.
	 * @param mandrakepkgs a transient instance containing updated state
	 * @param the Session
	 */
	public void update(pfe.migration.server.ejb.bdd.Mandrakepkgs mandrakepkgs, Session s)
		throws net.sf.hibernate.HibernateException {
		super.update(mandrakepkgs, s);
	}

	/**
	 * Remove a persistent instance from the datastore. The argument may be an instance associated with the receiving
	 * Session or a transient instance with an identifier associated with existing persistent state. 
	 * @param id the instance ID to be removed
	 */
	public void delete(java.lang.Long id)
		throws net.sf.hibernate.HibernateException {
		super.delete(load(id));
	}

	/**
	 * Remove a persistent instance from the datastore. The argument may be an instance associated with the receiving
	 * Session or a transient instance with an identifier associated with existing persistent state. 
	 * Use the Session given.
	 * @param id the instance ID to be removed
	 * @param s the Session
	 */
	public void delete(java.lang.Long id, Session s)
		throws net.sf.hibernate.HibernateException {
		super.delete(load(id, s), s);
	}

	/**
	 * Remove a persistent instance from the datastore. The argument may be an instance associated with the receiving
	 * Session or a transient instance with an identifier associated with existing persistent state. 
	 * @param mandrakepkgs the instance to be removed
	 */
	public void delete(pfe.migration.server.ejb.bdd.Mandrakepkgs mandrakepkgs)
		throws net.sf.hibernate.HibernateException {
		super.delete(mandrakepkgs);
	}

	/**
	 * Remove a persistent instance from the datastore. The argument may be an instance associated with the receiving
	 * Session or a transient instance with an identifier associated with existing persistent state. 
	 * Use the Session given.
	 * @param mandrakepkgs the instance to be removed
	 * @param s the Session
	 */
	public void delete(pfe.migration.server.ejb.bdd.Mandrakepkgs mandrakepkgs, Session s)
		throws net.sf.hibernate.HibernateException {
		super.delete(mandrakepkgs, s);
	}
	
	/**
	 * Re-read the state of the given instance from the underlying database. It is inadvisable to use this to implement
	 * long-running sessions that span many business tasks. This method is, however, useful in certain special circumstances.
	 * For example 
	 * <ul> 
	 * <li>where a database trigger alters the object state upon insert or update</li>
	 * <li>after executing direct SQL (eg. a mass update) in the same session</li>
	 * <li>after inserting a Blob or Clob</li>
	 * </ul>
	 */
	public void refresh (pfe.migration.server.ejb.bdd.Mandrakepkgs mandrakepkgs, Session s)
		throws net.sf.hibernate.HibernateException {
		super.refresh(mandrakepkgs, s);
	}

    public String getDefaultOrderProperty () {
		return "Name";
    }

}