package pfe.migration.server.ejb.bdd.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the GLOBAL_CONF table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="GLOBAL_CONF"
 */
public abstract class BaseGlobalConf  implements Serializable {

	public static String PROP_GLOBAL_DOMAIN_NAME = "GlobalDomainName";
	public static String PROP_GLOBAL_HOSTNAME = "GlobalHostname";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _globalDomainName;
	private java.lang.String _globalHostname;


	// constructors
	public BaseGlobalConf () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseGlobalConf (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="GLOBAL_ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: GLOBAL_DOMAIN_NAME
	 */
	public java.lang.String getGlobalDomainName () {
		return _globalDomainName;
	}

	/**
	 * Set the value related to the column: GLOBAL_DOMAIN_NAME
	 * @param _globalDomainName the GLOBAL_DOMAIN_NAME value
	 */
	public void setGlobalDomainName (java.lang.String _globalDomainName) {
		this._globalDomainName = _globalDomainName;
	}


	/**
	 * Return the value associated with the column: GLOBAL_HOSTNAME
	 */
	public java.lang.String getGlobalHostname () {
		return _globalHostname;
	}

	/**
	 * Set the value related to the column: GLOBAL_HOSTNAME
	 * @param _globalHostname the GLOBAL_HOSTNAME value
	 */
	public void setGlobalHostname (java.lang.String _globalHostname) {
		this._globalHostname = _globalHostname;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof pfe.migration.server.ejb.bdd.base.BaseGlobalConf)) return false;
		else {
			pfe.migration.server.ejb.bdd.base.BaseGlobalConf mObj = (pfe.migration.server.ejb.bdd.base.BaseGlobalConf) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}