package pfe.migration.server.ejb.bdd.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the USERS_DATA table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="USERS_DATA"
 */
public abstract class BaseUsersData  implements Serializable {

	public static String PROP_USER_PASS = "UserPass";
	public static String PROP_USER_PROXY_SERV = "UserProxyServ";
	public static String PROP_USER_PROXY_OVERRIDE = "UserProxyOverride";
	public static String PROP_USER_TYPE = "UserType";
	public static String PROP_USER_BGIMG = "UserBgimg";
	public static String PROP_USER_LOGIN = "UserLogin";
	public static String PROP_USER_KEY = "UserKey";
	public static String PROP_USER_HOME = "UserHome";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _userProxyServ;
	private java.lang.String _userType;
	private java.lang.String _userProxyOverride;
	private java.lang.String _userHome;
	private java.lang.String _userBgimg;
	private java.lang.String _userLogin;
	private java.lang.String _userPass;
	private java.lang.Integer _userKey;


	// constructors
	public BaseUsersData () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseUsersData (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="vm"
     *  column="USER_ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: USER_PROXY_SERV
	 */
	public java.lang.String getUserProxyServ () {
		return _userProxyServ;
	}

	/**
	 * Set the value related to the column: USER_PROXY_SERV
	 * @param _userProxyServ the USER_PROXY_SERV value
	 */
	public void setUserProxyServ (java.lang.String _userProxyServ) {
		this._userProxyServ = _userProxyServ;
	}


	/**
	 * Return the value associated with the column: USER_TYPE
	 */
	public java.lang.String getUserType () {
		return _userType;
	}

	/**
	 * Set the value related to the column: USER_TYPE
	 * @param _userType the USER_TYPE value
	 */
	public void setUserType (java.lang.String _userType) {
		this._userType = _userType;
	}


	/**
	 * Return the value associated with the column: USER_PROXY_OVERRIDE
	 */
	public java.lang.String getUserProxyOverride () {
		return _userProxyOverride;
	}

	/**
	 * Set the value related to the column: USER_PROXY_OVERRIDE
	 * @param _userProxyOverride the USER_PROXY_OVERRIDE value
	 */
	public void setUserProxyOverride (java.lang.String _userProxyOverride) {
		this._userProxyOverride = _userProxyOverride;
	}


	/**
	 * Return the value associated with the column: USER_HOME
	 */
	public java.lang.String getUserHome () {
		return _userHome;
	}

	/**
	 * Set the value related to the column: USER_HOME
	 * @param _userHome the USER_HOME value
	 */
	public void setUserHome (java.lang.String _userHome) {
		this._userHome = _userHome;
	}


	/**
	 * Return the value associated with the column: USER_BGIMG
	 */
	public java.lang.String getUserBgimg () {
		return _userBgimg;
	}

	/**
	 * Set the value related to the column: USER_BGIMG
	 * @param _userBgimg the USER_BGIMG value
	 */
	public void setUserBgimg (java.lang.String _userBgimg) {
		this._userBgimg = _userBgimg;
	}


	/**
	 * Return the value associated with the column: USER_LOGIN
	 */
	public java.lang.String getUserLogin () {
		return _userLogin;
	}

	/**
	 * Set the value related to the column: USER_LOGIN
	 * @param _userLogin the USER_LOGIN value
	 */
	public void setUserLogin (java.lang.String _userLogin) {
		this._userLogin = _userLogin;
	}


	/**
	 * Return the value associated with the column: USER_PASS
	 */
	public java.lang.String getUserPass () {
		return _userPass;
	}

	/**
	 * Set the value related to the column: USER_PASS
	 * @param _userPass the USER_PASS value
	 */
	public void setUserPass (java.lang.String _userPass) {
		this._userPass = _userPass;
	}


	/**
	 * Return the value associated with the column: USER_KEY
	 */
	public java.lang.Integer getUserKey () {
		return _userKey;
	}

	/**
	 * Set the value related to the column: USER_KEY
	 * @param _userKey the USER_KEY value
	 */
	public void setUserKey (java.lang.Integer _userKey) {
		this._userKey = _userKey;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof pfe.migration.server.ejb.bdd.base.BaseUsersData)) return false;
		else {
			pfe.migration.server.ejb.bdd.base.BaseUsersData mObj = (pfe.migration.server.ejb.bdd.base.BaseUsersData) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}