// wwi.h

#pragma once

using namespace System;

namespace wwi {

	public ref class Class1
	{
		// TODO: Add your methods for this class here.
	};
}


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pfe_migration_client_pre_service_WanduxWmiBridge */

#ifndef _Included_pfe_migration_client_pre_service_WanduxWmiBridge
#define _Included_pfe_migration_client_pre_service_WanduxWmiBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pfe_migration_client_pre_service_WanduxWmiBridge
 * Method:    toto
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pfe_migration_client_pre_service_WanduxWmiBridge_toto
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

