package pfe.migration.server.ejb.bdd.dao;

import pfe.migration.server.ejb.bdd.base.BaseNetworkDhcpConfigDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the network_dhcp_config table.
 * Any customizations belong here.
 */
public class NetworkDhcpConfigDAO extends BaseNetworkDhcpConfigDAO {
}